/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddressSelector: typeof import('./components/AddressSelector.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    DoctorCard: typeof import('./components/DoctorCard.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    HealthConcernSelector: typeof import('./components/HealthConcernSelector.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PaymentMethodSelector: typeof import('./components/PaymentMethodSelector.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCard: typeof import('wot-design-uni/components/wd-card/wd-card.vue')['default']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['default']
    WdEmpty: typeof import('wot-design-uni/components/wd-empty/wd-empty.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdRadio: typeof import('wot-design-uni/components/wd-radio/wd-radio.vue')['default']
    WdRadioGroup: typeof import('wot-design-uni/components/wd-radio-group/wd-radio-group.vue')['default']
    WdSearch: typeof import('wot-design-uni/components/wd-search/wd-search.vue')['default']
    WdStepper: typeof import('wot-design-uni/components/wd-stepper/wd-stepper.vue')['default']
    WdSteps: typeof import('wot-design-uni/components/wd-steps/wd-steps.vue')['default']
    WdSticky: typeof import('wot-design-uni/components/wd-sticky/wd-sticky.vue')['default']
    WdTab: typeof import('wot-design-uni/components/wd-tab/wd-tab.vue')['default']
    WdTabs: typeof import('wot-design-uni/components/wd-tabs/wd-tabs.vue')['default']
    WdTag: typeof import('wot-design-uni/components/wd-tag/wd-tag.vue')['default']
  }
}
