/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/all-doctors" |
  "/pages/consultation-order" |
  "/pages/consultation-record-detail" |
  "/pages/consultation-records" |
  "/pages/doctor-detail" |
  "/pages/im-chat" |
  "/pages/online-clinic" |
  "/pages/patient-profile" |
  "/pages/payment-order" |
  "/pages/pharmacy" |
  "/pages/prescription-detail" |
  "/pages/prescription-records" |
  "/pages/wot-test";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
