/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 国浩中医 - version 1.0.0
 *
 * &lt;br/&gt;&lt;u&gt;&lt;b&gt;&lt;font color&#x3D;&#x27;FF0000&#x27;&gt; 👮2001972@qq.com &lt;/font&gt;&lt;/b&gt;&lt;/u&gt;
 *
 * OpenAPI version: 3.0.4
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'app_HealthArticleTag.apiApp_healtharticletagProcesstagsTagsjsonPost': [
    'POST',
    '/api/app_HealthArticleTag/processTags/{tagsJson}'
  ],
  'app_HealthArticle.apiApp_healtharticleSyncolddataPost': ['POST', '/api/app_HealthArticle/syncOldData'],
  'app_healthskill.apiApp_healthskillSynchealthskillPost': ['POST', '/api/app_healthskill/syncHealthskill'],
  'appSysDictData.apiAppsysdictdataPagePost': ['POST', '/api/appSysDictData/page'],
  'appSysDictData.apiAppsysdictdataListGet': ['GET', '/api/appSysDictData/list'],
  'appSysDictData.apiAppsysdictdataDetailGet': ['GET', '/api/appSysDictData/detail'],
  'appSysDictData.apiAppsysdictdataDatalistCodeGet': ['GET', '/api/appSysDictData/dataList/{code}'],
  'appSysDictData.apiAppsysdictdataDatalistGet': ['GET', '/api/appSysDictData/dataList'],
  'appAuth.apiAppauthTestolddataPost': ['POST', '/api/appAuth/testolddata'],
  'appAuth.apiAppauthLoginPost': ['POST', '/api/appAuth/login'],
  'appAuth.apiAppauthGenimusersigUseridGet': ['GET', '/api/appAuth/genImUserSig/{userId}'],
  'appAuth.apiAppauthLoginbyphonePost': ['POST', '/api/appAuth/loginByPhone'],
  'appAuth.apiAppauthLoginbywechatPost': ['POST', '/api/appAuth/loginByWechat'],
  'appAuth.apiAppauthAppuserinfoGet': ['GET', '/api/appAuth/appUserInfo'],
  'appAuth.apiAppauthLogoutPost': ['POST', '/api/appAuth/logout'],
  'appUser.apiAppuserRegisterPost': ['POST', '/api/appUser/register'],
  'appUser.apiAppuserUserinfoPut': ['PUT', '/api/appUser/userInfo'],
  'appUser.apiAppuserVerifyforgetpasswordcodePost': ['POST', '/api/appUser/verifyForgetPasswordCode'],
  'appUser.apiAppuserResetpasswordPost': ['POST', '/api/appUser/resetPassword'],
  'appUser.apiAppuserCheckmobileregisteredandsendcodeGet': ['GET', '/api/appUser/checkMobileRegisteredAndSendCode'],
  'appUser.apiAppuserChangepasswordPost': ['POST', '/api/appUser/changePassword'],
  'appUser.apiAppuserUploadavatarPost': ['POST', '/api/appUser/uploadAvatar'],
  'appUser.apiAppuserSendsmscodeMobilePost': ['POST', '/api/appUser/sendSmsCode/{mobile}'],
  'appUser.apiAppuserCheckusernameavailableUsernamePost': ['POST', '/api/appUser/checkUsernameAvailable/{username}'],
  'appUser.apiAppuserCheckmobileavailableMobilePost': ['POST', '/api/appUser/checkMobileAvailable/{mobile}'],
  'app_Appointment.apiApp_appointmentPagePost': ['POST', '/api/app_Appointment/page'],
  'app_Appointment.apiApp_appointmentDetailGet': ['GET', '/api/app_Appointment/detail'],
  'app_Appointment.apiApp_appointmentAddPost': ['POST', '/api/app_Appointment/add'],
  'app_Appointment.apiApp_appointmentUpdatePost': ['POST', '/api/app_Appointment/update'],
  'app_Appointment.apiApp_appointmentDeletePost': ['POST', '/api/app_Appointment/delete'],
  'app_Appointment.apiApp_appointmentBatchdeletePost': ['POST', '/api/app_Appointment/batchDelete'],
  'app_Appointment.apiApp_appointmentDropdowndataPost': ['POST', '/api/app_Appointment/dropdownData'],
  'app_Appointment.apiApp_appointmentExportPost': ['POST', '/api/app_Appointment/export'],
  'app_Appointment.apiApp_appointmentImportGet': ['GET', '/api/app_Appointment/import'],
  'app_Appointment.apiApp_appointmentImportPost': ['POST', '/api/app_Appointment/import'],
  'app_DoctorAuditing.apiApp_doctorauditingPagePost': ['POST', '/api/app_DoctorAuditing/page'],
  'app_DoctorAuditing.apiApp_doctorauditingApppagePost': ['POST', '/api/app_DoctorAuditing/appPage'],
  'app_DoctorAuditing.apiApp_doctorauditingDetailGet': ['GET', '/api/app_DoctorAuditing/detail'],
  'app_DoctorAuditing.apiApp_doctorauditingAddPost': ['POST', '/api/app_DoctorAuditing/add'],
  'app_DoctorAuditing.apiApp_doctorauditingUpdatePost': ['POST', '/api/app_DoctorAuditing/update'],
  'app_DoctorAuditing.apiApp_doctorauditingDeletePost': ['POST', '/api/app_DoctorAuditing/delete'],
  'app_DoctorAuditing.apiApp_doctorauditingBatchdeletePost': ['POST', '/api/app_DoctorAuditing/batchDelete'],
  'app_DoctorAuditing.apiApp_doctorauditingUploadidcard_front_imagePost': [
    'POST',
    '/api/app_DoctorAuditing/uploadIdcard_front_image'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingUploadidcard_back_imagePost': [
    'POST',
    '/api/app_DoctorAuditing/uploadIdcard_back_image'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingUploadidcard_handheld_imagePost': [
    'POST',
    '/api/app_DoctorAuditing/uploadIdcard_handheld_image'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingUploaddoctor_qualification_imagesPost': [
    'POST',
    '/api/app_DoctorAuditing/uploadDoctor_qualification_images'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingUploadchn_medicine_qualification_imagesPost': [
    'POST',
    '/api/app_DoctorAuditing/uploadChn_medicine_qualification_images'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingDropdowndataPost': ['POST', '/api/app_DoctorAuditing/dropdownData'],
  'app_DoctorAuditing.apiApp_doctorauditingExportPost': ['POST', '/api/app_DoctorAuditing/export'],
  'app_DoctorAuditing.apiApp_doctorauditingImportGet': ['GET', '/api/app_DoctorAuditing/import'],
  'app_DoctorAuditing.apiApp_doctorauditingImportPost': ['POST', '/api/app_DoctorAuditing/import'],
  'app_DoctorAuditing.apiApp_doctorauditingMigratefromtdoctorauditingPost': [
    'POST',
    '/api/app_DoctorAuditing/migrateFromTDoctorAuditing'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingMigratefromtconsultantauditingPost': [
    'POST',
    '/api/app_DoctorAuditing/migrateFromTConsultantAuditing'
  ],
  'app_DoctorAuditing.apiApp_doctorauditingGetrecommendeddoctorsPost': [
    'POST',
    '/api/app_DoctorAuditing/getRecommendedDoctors'
  ],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryPagePost': ['POST', '/api/app_HealthArticleCategory/page'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryListGet': ['GET', '/api/app_HealthArticleCategory/list'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryTreeGet': ['GET', '/api/app_HealthArticleCategory/tree'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryDetailGet': ['GET', '/api/app_HealthArticleCategory/detail'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryAddPost': ['POST', '/api/app_HealthArticleCategory/add'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryUpdatePost': ['POST', '/api/app_HealthArticleCategory/update'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryDeletePost': ['POST', '/api/app_HealthArticleCategory/delete'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryBatchdeletePost': [
    'POST',
    '/api/app_HealthArticleCategory/batchDelete'
  ],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryExportPost': ['POST', '/api/app_HealthArticleCategory/export'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryImportGet': ['GET', '/api/app_HealthArticleCategory/import'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryImportPost': ['POST', '/api/app_HealthArticleCategory/import'],
  'app_HealthArticleTag.apiApp_healtharticletagPagePost': ['POST', '/api/app_HealthArticleTag/page'],
  'app_HealthArticleTag.apiApp_healtharticletagDetailGet': ['GET', '/api/app_HealthArticleTag/detail'],
  'app_HealthArticleTag.apiApp_healtharticletagAddPost': ['POST', '/api/app_HealthArticleTag/add'],
  'app_HealthArticleTag.apiApp_healtharticletagInitdataPost': ['POST', '/api/app_HealthArticleTag/initData'],
  'app_HealthArticleTag.apiApp_healtharticletagUpdatePost': ['POST', '/api/app_HealthArticleTag/update'],
  'app_HealthArticleTag.apiApp_healtharticletagDeletePost': ['POST', '/api/app_HealthArticleTag/delete'],
  'app_HealthArticleTag.apiApp_healtharticletagBatchdeletePost': ['POST', '/api/app_HealthArticleTag/batchDelete'],
  'app_HealthArticleTag.apiApp_healtharticletagExportPost': ['POST', '/api/app_HealthArticleTag/export'],
  'app_HealthArticleTag.apiApp_healtharticletagImportGet': ['GET', '/api/app_HealthArticleTag/import'],
  'app_HealthArticleTag.apiApp_healtharticletagImportPost': ['POST', '/api/app_HealthArticleTag/import'],
  'app_HealthArticle.apiApp_healtharticlePagePost': ['POST', '/api/app_HealthArticle/page'],
  'app_HealthArticle.apiApp_healtharticleDetailGet': ['GET', '/api/app_HealthArticle/detail'],
  'app_HealthArticle.apiApp_healtharticleAddPost': ['POST', '/api/app_HealthArticle/add'],
  'app_HealthArticle.apiApp_healtharticleUpdatePost': ['POST', '/api/app_HealthArticle/update'],
  'app_HealthArticle.apiApp_healtharticleDeletePost': ['POST', '/api/app_HealthArticle/delete'],
  'app_HealthArticle.apiApp_healtharticleBatchdeletePost': ['POST', '/api/app_HealthArticle/batchDelete'],
  'app_HealthArticle.apiApp_healtharticleUploadcoverimageurlPost': [
    'POST',
    '/api/app_HealthArticle/uploadCoverImageUrl'
  ],
  'app_HealthArticle.apiApp_healtharticleUploadimageurlsPost': ['POST', '/api/app_HealthArticle/uploadImageUrls'],
  'app_HealthArticle.apiApp_healtharticleUploadvideourlPost': ['POST', '/api/app_HealthArticle/uploadVideoUrl'],
  'app_HealthArticle.apiApp_healtharticleDropdowndataPost': ['POST', '/api/app_HealthArticle/dropdownData'],
  'app_HealthArticle.apiApp_healtharticleExportPost': ['POST', '/api/app_HealthArticle/export'],
  'app_HealthArticle.apiApp_healtharticleImportGet': ['GET', '/api/app_HealthArticle/import'],
  'app_HealthArticle.apiApp_healtharticleImportPost': ['POST', '/api/app_HealthArticle/import'],
  'app_HealthArticle.apiApp_healtharticleFavoriteArticleidUseridPost': [
    'POST',
    '/api/app_HealthArticle/favorite/{articleId}/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleLikeArticleidUseridPost': [
    'POST',
    '/api/app_HealthArticle/like/{articleId}/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleGetuserfavoritesUseridGet': [
    'GET',
    '/api/app_HealthArticle/getUserFavorites/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleUpdatetagstonamesPost': ['POST', '/api/app_HealthArticle/updateTagsToNames'],
  'app_healthskill.apiApp_healthskillPagePost': ['POST', '/api/app_healthskill/page'],
  'app_healthskill.apiApp_healthskillDetailGet': ['GET', '/api/app_healthskill/detail'],
  'app_healthskill.apiApp_healthskillAddPost': ['POST', '/api/app_healthskill/add'],
  'app_healthskill.apiApp_healthskillUpdatePost': ['POST', '/api/app_healthskill/update'],
  'app_healthskill.apiApp_healthskillDeletePost': ['POST', '/api/app_healthskill/delete'],
  'app_healthskill.apiApp_healthskillBatchdeletePost': ['POST', '/api/app_healthskill/batchDelete'],
  'app_healthskill.apiApp_healthskillExportPost': ['POST', '/api/app_healthskill/export'],
  'app_healthskill.apiApp_healthskillImportGet': ['GET', '/api/app_healthskill/import'],
  'app_healthskill.apiApp_healthskillImportPost': ['POST', '/api/app_healthskill/import'],
  'app_healthskill.apiApp_healthskillRandomGet': ['GET', '/api/app_healthskill/random'],
  'app_Medicine.apiApp_medicinePagePost': ['POST', '/api/app_Medicine/page'],
  'app_Medicine.apiApp_medicineDetailGet': ['GET', '/api/app_Medicine/detail'],
  'app_Medicine.apiApp_medicineAddPost': ['POST', '/api/app_Medicine/add'],
  'app_Medicine.apiApp_medicineUpdatePost': ['POST', '/api/app_Medicine/update'],
  'app_Medicine.apiApp_medicineDeletePost': ['POST', '/api/app_Medicine/delete'],
  'app_Medicine.apiApp_medicineBatchdeletePost': ['POST', '/api/app_Medicine/batchDelete'],
  'app_Medicine.apiApp_medicineExportPost': ['POST', '/api/app_Medicine/export'],
  'app_Medicine.apiApp_medicineImportGet': ['GET', '/api/app_Medicine/import'],
  'app_Medicine.apiApp_medicineImportPost': ['POST', '/api/app_Medicine/import'],
  'app_Medicine.apiApp_medicineSyncolddataPost': ['POST', '/api/app_Medicine/syncOldData'],
  'app_Message.apiApp_messagePagePost': ['POST', '/api/app_Message/page'],
  'app_Message.apiApp_messageDetailGet': ['GET', '/api/app_Message/detail'],
  'app_Message.apiApp_messageAddPost': ['POST', '/api/app_Message/add'],
  'app_Message.apiApp_messageUpdatePost': ['POST', '/api/app_Message/update'],
  'app_Message.apiApp_messageDeletePost': ['POST', '/api/app_Message/delete'],
  'app_Message.apiApp_messageBatchdeletePost': ['POST', '/api/app_Message/batchDelete'],
  'app_Message.apiApp_messageDropdowndataPost': ['POST', '/api/app_Message/dropdownData'],
  'app_Message.apiApp_messageExportPost': ['POST', '/api/app_Message/export'],
  'app_Message.apiApp_messageImportGet': ['GET', '/api/app_Message/import'],
  'app_Message.apiApp_messageImportPost': ['POST', '/api/app_Message/import'],
  'app_Message.apiApp_messageMarkasreadMessageidPost': ['POST', '/api/app_Message/markAsRead/{messageId}'],
  'app_PaymentTransaction.apiApp_paymenttransactionPagePost': ['POST', '/api/app_PaymentTransaction/page'],
  'app_PaymentTransaction.apiApp_paymenttransactionDetailGet': ['GET', '/api/app_PaymentTransaction/detail'],
  'app_PaymentTransaction.apiApp_paymenttransactionAddPost': ['POST', '/api/app_PaymentTransaction/add'],
  'app_PaymentTransaction.apiApp_paymenttransactionUpdatePost': ['POST', '/api/app_PaymentTransaction/update'],
  'app_PaymentTransaction.apiApp_paymenttransactionDeletePost': ['POST', '/api/app_PaymentTransaction/delete'],
  'app_PaymentTransaction.apiApp_paymenttransactionBatchdeletePost': [
    'POST',
    '/api/app_PaymentTransaction/batchDelete'
  ],
  'app_PaymentTransaction.apiApp_paymenttransactionExportPost': ['POST', '/api/app_PaymentTransaction/export'],
  'app_PaymentTransaction.apiApp_paymenttransactionImportGet': ['GET', '/api/app_PaymentTransaction/import'],
  'app_PaymentTransaction.apiApp_paymenttransactionImportPost': ['POST', '/api/app_PaymentTransaction/import'],
  'app_Prescription.apiApp_prescriptionPagePost': ['POST', '/api/app_Prescription/page'],
  'app_Prescription.apiApp_prescriptionDetailGet': ['GET', '/api/app_Prescription/detail'],
  'app_Prescription.apiApp_prescriptionAddPost': ['POST', '/api/app_Prescription/add'],
  'app_Prescription.apiApp_prescriptionUpdatePost': ['POST', '/api/app_Prescription/update'],
  'app_Prescription.apiApp_prescriptionDeletePost': ['POST', '/api/app_Prescription/delete'],
  'app_Prescription.apiApp_prescriptionBatchdeletePost': ['POST', '/api/app_Prescription/batchDelete'],
  'app_Prescription.apiApp_prescriptionExportPost': ['POST', '/api/app_Prescription/export'],
  'app_Prescription.apiApp_prescriptionImportGet': ['GET', '/api/app_Prescription/import'],
  'app_Prescription.apiApp_prescriptionImportPost': ['POST', '/api/app_Prescription/import'],
  'app_User.apiApp_userPagePost': ['POST', '/api/app_User/page'],
  'app_User.apiApp_userDetailGet': ['GET', '/api/app_User/detail'],
  'app_User.apiApp_userAddPost': ['POST', '/api/app_User/add'],
  'app_User.apiApp_userUpdatePost': ['POST', '/api/app_User/update'],
  'app_User.apiApp_userDeletePost': ['POST', '/api/app_User/delete'],
  'app_User.apiApp_userBatchdeletePost': ['POST', '/api/app_User/batchDelete'],
  'app_User.apiApp_userSetstatusPost': ['POST', '/api/app_User/setStatus'],
  'app_User.apiApp_userUploadavatarPost': ['POST', '/api/app_User/uploadAvatar'],
  'app_User.apiApp_userExportPost': ['POST', '/api/app_User/export'],
  'app_User.apiApp_userImportGet': ['GET', '/api/app_User/import'],
  'app_User.apiApp_userImportPost': ['POST', '/api/app_User/import']
};
