/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * APP - version 1.0.0
 *
 * &lt;br/&gt;&lt;u&gt;&lt;b&gt;&lt;font color&#x3D;&#x27;FF0000&#x27;&gt; 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;
 *
 * OpenAPI version: 3.0.4
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'app.apiAppRegisterPost': ['POST', '/api/app/register'],
  'app.apiAppUserinfoPut': ['PUT', '/api/app/userInfo'],
  'app.apiAppVerifyforgetpasswordcodePost': ['POST', '/api/app/verifyForgetPasswordCode'],
  'app.apiAppResetpasswordPost': ['POST', '/api/app/resetPassword'],
  'app.apiAppCheckmobileregisteredandsendcodeGet': ['GET', '/api/app/checkMobileRegisteredAndSendCode'],
  'app.apiAppChangepasswordPost': ['POST', '/api/app/changePassword'],
  'app.apiAppUploadavatarPost': ['POST', '/api/app/uploadAvatar'],
  'app.apiAppSendsmscodeMobilePost': ['POST', '/api/app/sendSmsCode/{mobile}'],
  'app.apiAppCheckusernameavailableUsernamePost': ['POST', '/api/app/checkUsernameAvailable/{username}'],
  'app.apiAppCheckmobileavailableMobilePost': ['POST', '/api/app/checkMobileAvailable/{mobile}'],
  'app.apiAppTestolddataPost': ['POST', '/api/app/testolddata'],
  'app.apiAppLoginPost': ['POST', '/api/app/login'],
  'app.apiAppGenimusersigUseridGet': ['GET', '/api/app/genImUserSig/{userId}'],
  'app.apiAppLoginbyphonePost': ['POST', '/api/app/loginByPhone'],
  'app.apiAppLoginbywechatPost': ['POST', '/api/app/loginByWechat'],
  'app.apiAppAppuserinfoGet': ['GET', '/api/app/appUserInfo'],
  'app.apiAppLogoutPost': ['POST', '/api/app/logout']
};
