/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 国浩中医 - version 1.0.0
 *
 * &lt;br/&gt;&lt;u&gt;&lt;b&gt;&lt;font color&#x3D;&#x27;FF0000&#x27;&gt; 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;
 *
 * OpenAPI version: 3.0.4
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'app_HealthArticleTag.apiApp_healtharticletagProcesstagsTagsjsonPost': [
    'POST',
    '/api/app_HealthArticleTag/processTags/{tagsJson}'
  ],
  'app_HealthArticle.apiApp_healtharticleSyncolddataPost': ['POST', '/api/app_HealthArticle/syncOldData'],
  'app_healthskill.apiApp_healthskillSynchealthskillPost': ['POST', '/api/app_healthskill/syncHealthskill'],
  'appAuth.apiAppauthTestolddataPost': ['POST', '/api/appAuth/testolddata'],
  'appAuth.apiAppauthLoginPost': ['POST', '/api/appAuth/login'],
  'appAuth.apiAppauthGenimusersigUseridGet': ['GET', '/api/appAuth/genImUserSig/{userId}'],
  'appAuth.apiAppauthLoginbyphonePost': ['POST', '/api/appAuth/loginByPhone'],
  'appAuth.apiAppauthLoginbywechatPost': ['POST', '/api/appAuth/loginByWechat'],
  'appAuth.apiAppauthAppuserinfoGet': ['GET', '/api/appAuth/appUserInfo'],
  'appAuth.apiAppauthLogoutPost': ['POST', '/api/appAuth/logout'],
  'appUser.apiAppuserRegisterPost': ['POST', '/api/appUser/register'],
  'appUser.apiAppuserUserinfoPut': ['PUT', '/api/appUser/userInfo'],
  'appUser.apiAppuserVerifyforgetpasswordcodePost': ['POST', '/api/appUser/verifyForgetPasswordCode'],
  'appUser.apiAppuserResetpasswordPost': ['POST', '/api/appUser/resetPassword'],
  'appUser.apiAppuserCheckmobileregisteredandsendcodeGet': ['GET', '/api/appUser/checkMobileRegisteredAndSendCode'],
  'appUser.apiAppuserChangepasswordPost': ['POST', '/api/appUser/changePassword'],
  'appUser.apiAppuserUploadavatarPost': ['POST', '/api/appUser/uploadAvatar'],
  'appUser.apiAppuserSendsmscodeMobilePost': ['POST', '/api/appUser/sendSmsCode/{mobile}'],
  'appUser.apiAppuserCheckusernameavailableUsernamePost': ['POST', '/api/appUser/checkUsernameAvailable/{username}'],
  'appUser.apiAppuserCheckmobileavailableMobilePost': ['POST', '/api/appUser/checkMobileAvailable/{mobile}'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryPagePost': ['POST', '/api/app_HealthArticleCategory/page'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryListGet': ['GET', '/api/app_HealthArticleCategory/list'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryTreeGet': ['GET', '/api/app_HealthArticleCategory/tree'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryDetailGet': ['GET', '/api/app_HealthArticleCategory/detail'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryAddPost': ['POST', '/api/app_HealthArticleCategory/add'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryUpdatePost': ['POST', '/api/app_HealthArticleCategory/update'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryDeletePost': ['POST', '/api/app_HealthArticleCategory/delete'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryBatchdeletePost': [
    'POST',
    '/api/app_HealthArticleCategory/batchDelete'
  ],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryExportPost': ['POST', '/api/app_HealthArticleCategory/export'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryImportGet': ['GET', '/api/app_HealthArticleCategory/import'],
  'app_HealthArticleCategory.apiApp_healtharticlecategoryImportPost': ['POST', '/api/app_HealthArticleCategory/import'],
  'app_HealthArticleTag.apiApp_healtharticletagPagePost': ['POST', '/api/app_HealthArticleTag/page'],
  'app_HealthArticleTag.apiApp_healtharticletagDetailGet': ['GET', '/api/app_HealthArticleTag/detail'],
  'app_HealthArticleTag.apiApp_healtharticletagAddPost': ['POST', '/api/app_HealthArticleTag/add'],
  'app_HealthArticleTag.apiApp_healtharticletagInitdataPost': ['POST', '/api/app_HealthArticleTag/initData'],
  'app_HealthArticleTag.apiApp_healtharticletagUpdatePost': ['POST', '/api/app_HealthArticleTag/update'],
  'app_HealthArticleTag.apiApp_healtharticletagDeletePost': ['POST', '/api/app_HealthArticleTag/delete'],
  'app_HealthArticleTag.apiApp_healtharticletagBatchdeletePost': ['POST', '/api/app_HealthArticleTag/batchDelete'],
  'app_HealthArticleTag.apiApp_healtharticletagExportPost': ['POST', '/api/app_HealthArticleTag/export'],
  'app_HealthArticleTag.apiApp_healtharticletagImportGet': ['GET', '/api/app_HealthArticleTag/import'],
  'app_HealthArticleTag.apiApp_healtharticletagImportPost': ['POST', '/api/app_HealthArticleTag/import'],
  'app_HealthArticle.apiApp_healtharticlePagePost': ['POST', '/api/app_HealthArticle/page'],
  'app_HealthArticle.apiApp_healtharticleDetailGet': ['GET', '/api/app_HealthArticle/detail'],
  'app_HealthArticle.apiApp_healtharticleAddPost': ['POST', '/api/app_HealthArticle/add'],
  'app_HealthArticle.apiApp_healtharticleUpdatePost': ['POST', '/api/app_HealthArticle/update'],
  'app_HealthArticle.apiApp_healtharticleDeletePost': ['POST', '/api/app_HealthArticle/delete'],
  'app_HealthArticle.apiApp_healtharticleBatchdeletePost': ['POST', '/api/app_HealthArticle/batchDelete'],
  'app_HealthArticle.apiApp_healtharticleUploadcoverimageurlPost': [
    'POST',
    '/api/app_HealthArticle/uploadCoverImageUrl'
  ],
  'app_HealthArticle.apiApp_healtharticleUploadimageurlsPost': ['POST', '/api/app_HealthArticle/uploadImageUrls'],
  'app_HealthArticle.apiApp_healtharticleUploadvideourlPost': ['POST', '/api/app_HealthArticle/uploadVideoUrl'],
  'app_HealthArticle.apiApp_healtharticleDropdowndataPost': ['POST', '/api/app_HealthArticle/dropdownData'],
  'app_HealthArticle.apiApp_healtharticleExportPost': ['POST', '/api/app_HealthArticle/export'],
  'app_HealthArticle.apiApp_healtharticleImportGet': ['GET', '/api/app_HealthArticle/import'],
  'app_HealthArticle.apiApp_healtharticleImportPost': ['POST', '/api/app_HealthArticle/import'],
  'app_HealthArticle.apiApp_healtharticleFavoriteArticleidUseridPost': [
    'POST',
    '/api/app_HealthArticle/favorite/{articleId}/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleLikeArticleidUseridPost': [
    'POST',
    '/api/app_HealthArticle/like/{articleId}/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleGetuserfavoritesUseridGet': [
    'GET',
    '/api/app_HealthArticle/getUserFavorites/{userId}'
  ],
  'app_HealthArticle.apiApp_healtharticleUpdatetagstonamesPost': ['POST', '/api/app_HealthArticle/updateTagsToNames'],
  'app_healthskill.apiApp_healthskillPagePost': ['POST', '/api/app_healthskill/page'],
  'app_healthskill.apiApp_healthskillDetailGet': ['GET', '/api/app_healthskill/detail'],
  'app_healthskill.apiApp_healthskillAddPost': ['POST', '/api/app_healthskill/add'],
  'app_healthskill.apiApp_healthskillUpdatePost': ['POST', '/api/app_healthskill/update'],
  'app_healthskill.apiApp_healthskillDeletePost': ['POST', '/api/app_healthskill/delete'],
  'app_healthskill.apiApp_healthskillBatchdeletePost': ['POST', '/api/app_healthskill/batchDelete'],
  'app_healthskill.apiApp_healthskillExportPost': ['POST', '/api/app_healthskill/export'],
  'app_healthskill.apiApp_healthskillImportGet': ['GET', '/api/app_healthskill/import'],
  'app_healthskill.apiApp_healthskillImportPost': ['POST', '/api/app_healthskill/import'],
  'app_healthskill.apiApp_healthskillRandomGet': ['GET', '/api/app_healthskill/random']
};
