/* tslint:disable */
/* eslint-disable */
/**
 * APP - version 1.0.0
 *
 * &lt;br/&gt;&lt;u&gt;&lt;b&gt;&lt;font color&#x3D;&#x27;FF0000&#x27;&gt; 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;
 *
 * OpenAPI version: 3.0.4
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type GenderEnum = 0 | 1 | 2 | 9;
export interface AppRegisterInput {
  /**
   * 用户名
   */
  username?: string | null;
  /**
   * 手机号码
   */
  mobile: string;
  /**
   * 验证码
   */
  code: string;
  /**
   * 密码
   */
  password: string;
  /**
   * 昵称
   */
  nickName?: string | null;
  /**
   * 邮箱
   */
  email?: string | null;
  /**
   * 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
   */
  sex?: GenderEnum;
}
export interface AppUpdateUserInfoInput {
  /**
   * 昵称
   */
  nickName?: string | null;
  /**
   * 头像
   */
  avatar?: string | null;
  /**
   * 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
   */
  sex?: GenderEnum;
  /**
   * 出生日期
   */
  birthday?: string | null;
  /**
   * 地址
   */
  address?: string | null;
  /**
   * 个人简介
   */
  introduction?: string | null;
}
export interface AppVerifyForgetPasswordCodeInput {
  /**
   * 手机号码
   */
  mobile: string;
  /**
   * 验证码
   */
  code: string;
}
export interface AppResetPasswordInput {
  /**
   * 手机号码
   */
  mobile: string;
  /**
   * 临时重置Token
   */
  resetToken: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface AppChangePasswordInput {
  /**
   * 旧密码
   */
  oldPassword: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface AppLoginInput {
  /**
   * 用户名/手机号/邮箱
   */
  account: string;
  /**
   * 密码
   */
  password: string;
  /**
   * 登录渠道
   */
  loginFrom?: string | null;
}
export interface AppPhoneLoginInput {
  /**
   * 手机号码
   */
  mobile: string;
  /**
   * 验证码
   */
  code: string;
  /**
   * 登录渠道
   */
  loginFrom?: string | null;
}
export interface WxUserInfo {
  /**
   * 昵称
   */
  nickName?: string | null;
  /**
   * 头像
   */
  avatarUrl?: string | null;
  /**
   * 性别
   */
  gender?: number;
  /**
   * 国家
   */
  country?: string | null;
  /**
   * 省份
   */
  province?: string | null;
  /**
   * 城市
   */
  city?: string | null;
}
export interface AppWxLoginInput {
  /**
   * 微信OpenId
   */
  openId: string;
  /**
   * 微信UnionId
   */
  unionId?: string | null;
  /**
   * 微信用户信息
   */
  userInfo?: WxUserInfo;
  /**
   * 登录渠道
   */
  loginFrom?: string | null;
}
export type AppAccountTypeEnum = 666 | 777 | 888 | 999;
export type AppRoleEnum = 666 | 777 | 888 | 999;
export type AuditEnum = 0 | 1;
export type StatusEnum = 1 | 2;
export interface App_UserRole {
  /**
   * 雪花Id
   */
  id?: number;
  /**
   * 用户Id
   */
  userId?: number;
  /**
   * APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
   */
  role?: AppRoleEnum;
  /**
   * 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
   */
  auditStatus?: AuditEnum;
  /**
   * 备注
   */
  remark?: string | null;
  /**
   * 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
   */
  status?: StatusEnum;
}
export interface AppUserInfo {
  /**
   * 用户ID
   */
  id?: number;
  /**
   * 用户名
   */
  username?: string | null;
  /**
   * 昵称
   */
  nickName?: string | null;
  /**
   * 头像
   */
  avatar?: string | null;
  /**
   * 手机号
   */
  mobile?: string | null;
  /**
   * 邮箱
   */
  email?: string | null;
  /**
   * 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
   */
  sex?: GenderEnum;
  /**
   * APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
   */
  accountType?: AppAccountTypeEnum;
  /**
   * APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
   */
  defaultRole?: AppRoleEnum;
  /**
   * 用户角色（JSON格式）
   */
  role?: App_UserRole[] | null;
  /**
   * 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
   */
  status?: StatusEnum;
  /**
   * 积分
   */
  score?: number;
  /**
   * 注册时间
   */
  registerDate?: string | null;
  /**
   * 最后登录时间
   */
  lastLoginTime?: string | null;
}
export interface AdminResult_AppUserInfo {
  /**
   * 状态码
   */
  code?: number;
  /**
   * 类型success、warning、error
   */
  type?: string | null;
  /**
   * 错误信息
   */
  message?: string | null;
  /**
   * APP用户信息
   */
  result?: AppUserInfo;
  /**
   * 附加数据
   */
  extras?: null;
  /**
   * 时间
   */
  time?: string;
}
export interface AdminResult_String {
  /**
   * 状态码
   */
  code?: number;
  /**
   * 类型success、warning、error
   */
  type?: string | null;
  /**
   * 错误信息
   */
  message?: string | null;
  /**
   * 数据
   */
  result?: string | null;
  /**
   * 附加数据
   */
  extras?: null;
  /**
   * 时间
   */
  time?: string;
}
export interface AdminResult_Boolean {
  /**
   * 状态码
   */
  code?: number;
  /**
   * 类型success、warning、error
   */
  type?: string | null;
  /**
   * 错误信息
   */
  message?: string | null;
  /**
   * 数据
   */
  result?: boolean;
  /**
   * 附加数据
   */
  extras?: null;
  /**
   * 时间
   */
  time?: string;
}
export interface AppLoginOutput {
  /**
   * 访问令牌
   */
  accessToken?: string | null;
  /**
   * 刷新令牌
   */
  refreshToken?: string | null;
  /**
   * 过期时间
   */
  expiresIn?: number;
  /**
   * APP用户信息
   */
  userInfo?: AppUserInfo;
  /**
   * 用户登录即时通信 IM 时使用的密码
   */
  userSig?: string | null;
}
export interface AdminResult_AppLoginOutput {
  /**
   * 状态码
   */
  code?: number;
  /**
   * 类型success、warning、error
   */
  type?: string | null;
  /**
   * 错误信息
   */
  message?: string | null;
  /**
   * APP登录输出
   */
  result?: AppLoginOutput;
  /**
   * 附加数据
   */
  extras?: null;
  /**
   * 时间
   */
  time?: string;
}
declare global {
  interface Apis {
    app: {
      /**
       * ---
       *
       * [POST] APP用户注册 🔖
       *
       * **path:** /api/app/register
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户名
       *   username?: string | null
       *   // 手机号码
       *   mobile: string
       *   // 验证码
       *   code: string
       *   // 密码
       *   password: string
       *   // 昵称
       *   nickName?: string | null
       *   // 邮箱
       *   email?: string | null
       *   // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *   sex?: 0 | 1 | 2 | 9
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP用户信息
       *   result?: {
       *     // 用户ID
       *     id?: number
       *     // 用户名
       *     username?: string | null
       *     // 昵称
       *     nickName?: string | null
       *     // 头像
       *     avatar?: string | null
       *     // 手机号
       *     mobile?: string | null
       *     // 邮箱
       *     email?: string | null
       *     // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *     sex?: 0 | 1 | 2 | 9
       *     // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *     accountType?: 666 | 777 | 888 | 999
       *     // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *     defaultRole?: 666 | 777 | 888 | 999
       *     // 用户角色（JSON格式）
       *     // [params1] start
       *     // [items] start
       *     // APP用户角色表
       *     // [items] end
       *     // [params1] end
       *     role?: Array<{
       *       // 雪花Id
       *       id?: number
       *       // 用户Id
       *       userId?: number
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       role?: 666 | 777 | 888 | 999
       *       // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *       auditStatus?: 0 | 1
       *       // 备注
       *       remark?: string | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *     }> | null
       *     // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *     status?: 1 | 2
       *     // 积分
       *     score?: number
       *     // 注册时间
       *     registerDate?: string | null
       *     // 最后登录时间
       *     lastLoginTime?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppRegisterPost<
        Config extends Alova2MethodConfig<AdminResult_AppUserInfo> & {
          data: AppRegisterInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_AppUserInfo, 'app.apiAppRegisterPost', Config>;
      /**
       * ---
       *
       * [PUT] 更新APP用户信息 🔖
       *
       * **path:** /api/app/userInfo
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 昵称
       *   nickName?: string | null
       *   // 头像
       *   avatar?: string | null
       *   // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *   sex?: 0 | 1 | 2 | 9
       *   // 出生日期
       *   birthday?: string | null
       *   // 地址
       *   address?: string | null
       *   // 个人简介
       *   introduction?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP用户信息
       *   result?: {
       *     // 用户ID
       *     id?: number
       *     // 用户名
       *     username?: string | null
       *     // 昵称
       *     nickName?: string | null
       *     // 头像
       *     avatar?: string | null
       *     // 手机号
       *     mobile?: string | null
       *     // 邮箱
       *     email?: string | null
       *     // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *     sex?: 0 | 1 | 2 | 9
       *     // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *     accountType?: 666 | 777 | 888 | 999
       *     // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *     defaultRole?: 666 | 777 | 888 | 999
       *     // 用户角色（JSON格式）
       *     // [params1] start
       *     // [items] start
       *     // APP用户角色表
       *     // [items] end
       *     // [params1] end
       *     role?: Array<{
       *       // 雪花Id
       *       id?: number
       *       // 用户Id
       *       userId?: number
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       role?: 666 | 777 | 888 | 999
       *       // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *       auditStatus?: 0 | 1
       *       // 备注
       *       remark?: string | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *     }> | null
       *     // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *     status?: 1 | 2
       *     // 积分
       *     score?: number
       *     // 注册时间
       *     registerDate?: string | null
       *     // 最后登录时间
       *     lastLoginTime?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppUserinfoPut<
        Config extends Alova2MethodConfig<AdminResult_AppUserInfo> & {
          data: AppUpdateUserInfoInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_AppUserInfo, 'app.apiAppUserinfoPut', Config>;
      /**
       * ---
       *
       * [POST] 校验忘记密码验证码 🔖
       *
       * **path:** /api/app/verifyForgetPasswordCode
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号码
       *   mobile: string
       *   // 验证码
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: string | null
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppVerifyforgetpasswordcodePost<
        Config extends Alova2MethodConfig<AdminResult_String> & {
          data: AppVerifyForgetPasswordCodeInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_String, 'app.apiAppVerifyforgetpasswordcodePost', Config>;
      /**
       * ---
       *
       * [POST] 重置密码（通过手机+resetToken）🔖
       *
       * **path:** /api/app/resetPassword
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号码
       *   mobile: string
       *   // 临时重置Token
       *   resetToken: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppResetpasswordPost<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          data: AppResetPasswordInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppResetpasswordPost', Config>;
      /**
       * ---
       *
       * [GET] 检查手机号已注册并发送验证码 🔖
       *
       * **path:** /api/app/checkMobileRegisteredAndSendCode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mobile: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppCheckmobileregisteredandsendcodeGet<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          params: {
            mobile: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppCheckmobileregisteredandsendcodeGet', Config>;
      /**
       * ---
       *
       * [POST] 修改APP用户密码 🔖
       *
       * **path:** /api/app/changePassword
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 旧密码
       *   oldPassword: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppChangepasswordPost<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          data: AppChangePasswordInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppChangepasswordPost', Config>;
      /**
       * ---
       *
       * [POST] 上传APP用户头像 🔖
       *
       * **path:** /api/app/uploadAvatar
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   file: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: string | null
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppUploadavatarPost<
        Config extends Alova2MethodConfig<AdminResult_String> & {
          data: {
            file: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_String, 'app.apiAppUploadavatarPost', Config>;
      /**
       * ---
       *
       * [POST] 发送手机验证码 🔖
       *
       * **path:** /api/app/sendSmsCode/{mobile}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   mobile: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppSendsmscodeMobilePost<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          pathParams: {
            mobile: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppSendsmscodeMobilePost', Config>;
      /**
       * ---
       *
       * [POST] 检查用户名是否可用 🔖
       *
       * **path:** /api/app/checkUsernameAvailable/{username}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppCheckusernameavailableUsernamePost<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          pathParams: {
            username: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppCheckusernameavailableUsernamePost', Config>;
      /**
       * ---
       *
       * [POST] 检查手机号是否可用 🔖
       *
       * **path:** /api/app/checkMobileAvailable/{mobile}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   mobile: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: boolean
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppCheckmobileavailableMobilePost<
        Config extends Alova2MethodConfig<AdminResult_Boolean> & {
          pathParams: {
            mobile: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_Boolean, 'app.apiAppCheckmobileavailableMobilePost', Config>;
      /**
       * ---
       *
       * [POST] APP账号密码登录 🔖
       *
       * **path:** /api/app/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户名/手机号/邮箱
       *   account: string
       *   // 密码
       *   password: string
       *   // 登录渠道
       *   loginFrom?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP登录输出
       *   result?: {
       *     // 访问令牌
       *     accessToken?: string | null
       *     // 刷新令牌
       *     refreshToken?: string | null
       *     // 过期时间
       *     expiresIn?: number
       *     // APP用户信息
       *     userInfo?: {
       *       // 用户ID
       *       id?: number
       *       // 用户名
       *       username?: string | null
       *       // 昵称
       *       nickName?: string | null
       *       // 头像
       *       avatar?: string | null
       *       // 手机号
       *       mobile?: string | null
       *       // 邮箱
       *       email?: string | null
       *       // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *       sex?: 0 | 1 | 2 | 9
       *       // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *       accountType?: 666 | 777 | 888 | 999
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       defaultRole?: 666 | 777 | 888 | 999
       *       // 用户角色（JSON格式）
       *       // [params1] start
       *       // [items] start
       *       // APP用户角色表
       *       // [items] end
       *       // [params1] end
       *       role?: Array<{
       *         // 雪花Id
       *         id?: number
       *         // 用户Id
       *         userId?: number
       *         // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *         role?: 666 | 777 | 888 | 999
       *         // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *         auditStatus?: 0 | 1
       *         // 备注
       *         remark?: string | null
       *         // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *         status?: 1 | 2
       *       }> | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *       // 积分
       *       score?: number
       *       // 注册时间
       *       registerDate?: string | null
       *       // 最后登录时间
       *       lastLoginTime?: string | null
       *     }
       *     // 用户登录即时通信 IM 时使用的密码
       *     userSig?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppLoginPost<
        Config extends Alova2MethodConfig<AdminResult_AppLoginOutput> & {
          data: AppLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_AppLoginOutput, 'app.apiAppLoginPost', Config>;
      /**
       * ---
       *
       * [GET] 计算腾讯IM签名 🔖
       *
       * **path:** /api/app/genImUserSig/{userId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // 数据
       *   result?: string | null
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppGenimusersigUseridGet<
        Config extends Alova2MethodConfig<AdminResult_String> & {
          pathParams: {
            userId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_String, 'app.apiAppGenimusersigUseridGet', Config>;
      /**
       * ---
       *
       * [POST] APP手机验证码登录 🔖
       *
       * **path:** /api/app/loginByPhone
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号码
       *   mobile: string
       *   // 验证码
       *   code: string
       *   // 登录渠道
       *   loginFrom?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP登录输出
       *   result?: {
       *     // 访问令牌
       *     accessToken?: string | null
       *     // 刷新令牌
       *     refreshToken?: string | null
       *     // 过期时间
       *     expiresIn?: number
       *     // APP用户信息
       *     userInfo?: {
       *       // 用户ID
       *       id?: number
       *       // 用户名
       *       username?: string | null
       *       // 昵称
       *       nickName?: string | null
       *       // 头像
       *       avatar?: string | null
       *       // 手机号
       *       mobile?: string | null
       *       // 邮箱
       *       email?: string | null
       *       // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *       sex?: 0 | 1 | 2 | 9
       *       // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *       accountType?: 666 | 777 | 888 | 999
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       defaultRole?: 666 | 777 | 888 | 999
       *       // 用户角色（JSON格式）
       *       // [params1] start
       *       // [items] start
       *       // APP用户角色表
       *       // [items] end
       *       // [params1] end
       *       role?: Array<{
       *         // 雪花Id
       *         id?: number
       *         // 用户Id
       *         userId?: number
       *         // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *         role?: 666 | 777 | 888 | 999
       *         // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *         auditStatus?: 0 | 1
       *         // 备注
       *         remark?: string | null
       *         // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *         status?: 1 | 2
       *       }> | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *       // 积分
       *       score?: number
       *       // 注册时间
       *       registerDate?: string | null
       *       // 最后登录时间
       *       lastLoginTime?: string | null
       *     }
       *     // 用户登录即时通信 IM 时使用的密码
       *     userSig?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppLoginbyphonePost<
        Config extends Alova2MethodConfig<AdminResult_AppLoginOutput> & {
          data: AppPhoneLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_AppLoginOutput, 'app.apiAppLoginbyphonePost', Config>;
      /**
       * ---
       *
       * [POST] APP微信登录 🔖
       *
       * **path:** /api/app/loginByWechat
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 微信OpenId
       *   openId: string
       *   // 微信UnionId
       *   unionId?: string | null
       *   // 微信用户信息
       *   userInfo?: {
       *     // 昵称
       *     nickName?: string | null
       *     // 头像
       *     avatarUrl?: string | null
       *     // 性别
       *     gender?: number
       *     // 国家
       *     country?: string | null
       *     // 省份
       *     province?: string | null
       *     // 城市
       *     city?: string | null
       *   }
       *   // 登录渠道
       *   loginFrom?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP登录输出
       *   result?: {
       *     // 访问令牌
       *     accessToken?: string | null
       *     // 刷新令牌
       *     refreshToken?: string | null
       *     // 过期时间
       *     expiresIn?: number
       *     // APP用户信息
       *     userInfo?: {
       *       // 用户ID
       *       id?: number
       *       // 用户名
       *       username?: string | null
       *       // 昵称
       *       nickName?: string | null
       *       // 头像
       *       avatar?: string | null
       *       // 手机号
       *       mobile?: string | null
       *       // 邮箱
       *       email?: string | null
       *       // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *       sex?: 0 | 1 | 2 | 9
       *       // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *       accountType?: 666 | 777 | 888 | 999
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       defaultRole?: 666 | 777 | 888 | 999
       *       // 用户角色（JSON格式）
       *       // [params1] start
       *       // [items] start
       *       // APP用户角色表
       *       // [items] end
       *       // [params1] end
       *       role?: Array<{
       *         // 雪花Id
       *         id?: number
       *         // 用户Id
       *         userId?: number
       *         // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *         role?: 666 | 777 | 888 | 999
       *         // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *         auditStatus?: 0 | 1
       *         // 备注
       *         remark?: string | null
       *         // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *         status?: 1 | 2
       *       }> | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *       // 积分
       *       score?: number
       *       // 注册时间
       *       registerDate?: string | null
       *       // 最后登录时间
       *       lastLoginTime?: string | null
       *     }
       *     // 用户登录即时通信 IM 时使用的密码
       *     userSig?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppLoginbywechatPost<
        Config extends Alova2MethodConfig<AdminResult_AppLoginOutput> & {
          data: AppWxLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<AdminResult_AppLoginOutput, 'app.apiAppLoginbywechatPost', Config>;
      /**
       * ---
       *
       * [GET] 获取APP用户信息 🔖
       *
       * **path:** /api/app/appUserInfo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 状态码
       *   code?: number
       *   // 类型success、warning、error
       *   type?: string | null
       *   // 错误信息
       *   message?: string | null
       *   // APP用户信息
       *   result?: {
       *     // 用户ID
       *     id?: number
       *     // 用户名
       *     username?: string | null
       *     // 昵称
       *     nickName?: string | null
       *     // 头像
       *     avatar?: string | null
       *     // 手机号
       *     mobile?: string | null
       *     // 邮箱
       *     email?: string | null
       *     // 性别枚举（GB/T 2261.1-2003）<br />&nbsp;未知的性别 Unknown = 0<br />&nbsp;男性 Male = 1<br />&nbsp;女性 Female = 2<br />&nbsp;未说明的性别 Unspecified = 9<br />
       *     sex?: 0 | 1 | 2 | 9
       *     // APP账号类型<br />&nbsp;会员 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
       *     accountType?: 666 | 777 | 888 | 999
       *     // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *     defaultRole?: 666 | 777 | 888 | 999
       *     // 用户角色（JSON格式）
       *     // [params1] start
       *     // [items] start
       *     // APP用户角色表
       *     // [items] end
       *     // [params1] end
       *     role?: Array<{
       *       // 雪花Id
       *       id?: number
       *       // 用户Id
       *       userId?: number
       *       // APP角色类型<br />&nbsp;代理 Agent = 666<br />&nbsp;普通 NormalUser = 777<br />&nbsp;医生 Doctor = 888<br />&nbsp;顾问 Consultant = 999<br />
       *       role?: 666 | 777 | 888 | 999
       *       // 认证状态<br />&nbsp;未认证 NotCertified = 0<br />&nbsp;已认证 Certified = 1<br />
       *       auditStatus?: 0 | 1
       *       // 备注
       *       remark?: string | null
       *       // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *       status?: 1 | 2
       *     }> | null
       *     // 通用状态枚举<br />&nbsp;启用 Enable = 1<br />&nbsp;停用 Disable = 2<br />
       *     status?: 1 | 2
       *     // 积分
       *     score?: number
       *     // 注册时间
       *     registerDate?: string | null
       *     // 最后登录时间
       *     lastLoginTime?: string | null
       *   }
       *   // 附加数据
       *   extras?: null
       *   // 时间
       *   time?: string
       * }
       * ```
       */
      apiAppAppuserinfoGet<Config extends Alova2MethodConfig<AdminResult_AppUserInfo>>(
        config?: Config
      ): Alova2Method<AdminResult_AppUserInfo, 'app.apiAppAppuserinfoGet', Config>;
      /**
       * ---
       *
       * [POST] APP退出登录 🔖
       *
       * **path:** /api/app/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      apiAppLogoutPost<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'app.apiAppLogoutPost', Config>;
    };
  }

  var Apis: Apis;
}
